import type { OnboardingQuestion } from "@/types/onboarding"

export const ONBOARDING_QUESTIONS: OnboardingQuestion[] = [
  {
    id: 1,
    category: "basic",
    question: "What's the name of your startup?",
    type: "text",
    required: true,
    followUp: false,
  },
  {
    id: 2,
    category: "basic",
    question: "In one sentence, what does your startup do?",
    type: "textarea",
    required: true,
    followUp: true,
  },
  {
    id: 3,
    category: "market",
    question: "Who is your target customer?",
    type: "textarea",
    required: true,
    followUp: true,
  },
  {
    id: 4,
    category: "market",
    question: "What problem are you solving?",
    type: "textarea",
    required: true,
    followUp: true,
  },
  {
    id: 5,
    category: "market",
    question: "How big is this problem? (How many people face this issue?)",
    type: "textarea",
    required: true,
    followUp: true,
  },
  {
    id: 6,
    category: "product",
    question: "What's your solution?",
    type: "textarea",
    required: true,
    followUp: true,
  },
  {
    id: 7,
    category: "product",
    question: "What stage is your product in?",
    type: "select",
    required: true,
    options: ["Idea only", "Prototype", "MVP", "Beta", "Live product", "Scaling"],
    followUp: true,
  },
  {
    id: 8,
    category: "business",
    question: "How do you plan to make money?",
    type: "textarea",
    required: true,
    followUp: true,
  },
  {
    id: 9,
    category: "business",
    question: "Who are your main competitors?",
    type: "textarea",
    required: true,
    followUp: true,
  },
  {
    id: 10,
    category: "business",
    question: "What makes you different from competitors?",
    type: "textarea",
    required: true,
    followUp: true,
  },
  {
    id: 11,
    category: "validation",
    question: "Have you talked to potential customers about this problem?",
    type: "select",
    required: true,
    options: ["Yes, extensively", "Yes, a few", "No, but planning to", "No"],
    followUp: true,
  },
  {
    id: 12,
    category: "validation",
    question: "Do you have any paying customers or pre-orders?",
    type: "select",
    required: true,
    options: ["Yes, paying customers", "Yes, pre-orders", "No, but have interest", "No"],
    followUp: true,
  },
  {
    id: 13,
    category: "business",
    question: "What's your biggest challenge right now?",
    type: "textarea",
    required: true,
    followUp: true,
  },
  {
    id: 14,
    category: "business",
    question: "What would success look like for you in 12 months?",
    type: "textarea",
    required: true,
    followUp: true,
  },
]
